#!/usr/bin/env bash

git remote set-url --add --push origin git@gitlab.bit9.local:carbonblack/integrations/airgap-connector
git remote set-url --add --push origin git@github.com:carbonblack/cb-airgap-connector.git
git remote set-url origin git@gitlab.bit9.local:carbonblack/integrations/airgap-connector.git
git remote -v
